name: "Podecast Generator"
autor: "Krishna Babu"
description: "Generate a feed for a podcast from a YAML file"
runs:
  using: "docker"
  iamge: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: "The commiter's email address"
    required: true
    default: ${{ githup.actor }}@localhost
  name:
    description: "The commiter's name"
    required: true
    default: ${{ githup.actor }}